name: automed_app
description: Automed - Global Healthcare Delivery Automation Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # UI Components
  cupertino_icons: ^1.0.6
  fl_chart: ^0.65.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.1
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # Navigation
  go_router: ^12.1.3
  auto_route: ^7.9.2

  # Network & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  connectivity_plus: ^5.0.2
  web_socket_channel: ^2.4.0

  # Local Storage & Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2

  # Authentication & Security
  local_auth: ^2.1.7
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1

  # Media & Files
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  cached_network_image: ^3.3.1
  permission_handler: ^11.2.0

  # Communication
  url_launcher: ^6.2.4
  share_plus: ^7.2.2
  flutter_phone_direct_caller: ^2.1.1

  # Firebase Services
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.7.4
  firebase_performance: ^0.9.3+8
  firebase_remote_config: ^4.3.8
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # Notifications
  flutter_local_notifications: ^16.3.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  logger: ^2.0.2+1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1

  # AI & ML
  tflite_flutter: ^0.10.4
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5

  # Charts & Analytics
  syncfusion_flutter_charts: ^24.1.41
  charts_flutter: ^0.12.0

  # Camera & Scanning
  camera: ^0.10.5+9
  qr_code_scanner: ^1.0.1
  barcode_scan2: ^4.3.3

  # Device Features
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  battery_plus: ^4.0.2
  sensors_plus: ^4.0.2

  # Development
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.3.9
  auto_route_generator: ^7.3.2

  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.3
  fake_async: ^1.3.1
  network_image_mock: ^2.1.1

  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Performance
  patrol: ^3.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/models/
    - assets/sounds/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.png
  branding: assets/images/splash_branding.png
  color_dark: "#042a49"
  image_dark: assets/images/splash_logo_dark.png
  branding_dark: assets/images/splash_branding_dark.png
  android_12:
    image: assets/images/splash_logo_android12.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/splash_logo_android12_dark.png
    icon_background_color_dark: "#042a49"
  web: false